name: Create release

on:
  push:
    branches:
      - main

jobs:
  create_release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read version
        id: read-version
        run: echo "version=$(jq -r '.version' package.json)" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create-release
        uses: invitation-homes/create-release-action@v1
        with:
          name: "v${{ steps.read-version.outputs.version }}"
          tag-name: "v${{ steps.read-version.outputs.version }}"
          github-token: ${{ secrets.GH_REPO_ACCESS_TOKEN }}
          draft: false
          pre-release: false
          generate-release-notes: true