name: "lint, build & test"
on: # rebuild any PRs and main branch changes (mirror few typescript-action conventions)
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      name: setup node
      with:
        node-version: '20.11'

    - name: "install"
      run: npm ci

    - name: "lint"
      run: npm run lint

    - name: "build"
      run: npm run build

    - name: "check for uncommitted changes"
      # Ensure no diff when built on ci
      # ignore node_modules since dev/fresh ci deps installed.
      run: |
        git diff --exit-code --stat -- . ':!node_modules' \
        || (echo "##[error] found changed files after build. please 'npm run build'" \
                  "and check in all changes" \
            && exit 1)

    - name: "archive lib when diff"
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: ci-built-lib
        path: lib/index.js

    - name: "test"
      run: npm run test

